<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id: company_youhui_sign.php 5695 2014-06-27 04:38:29Z youyi $
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
	'sign_id' => 
	array (
		'field' => 'sign_id',
		'label' => 'ID',
		'pk' => true,
		'add' => false,
		'edit' => false,
		'html' => false,
		'empty' => false,
		'show' => false,
		'list' => true,
		'type' => 'number',
		'comment' => '',
		'default' => '',
		'SO' => false,
	),
  'city_id' => 
	array (
		'field' => 'city_id',
		'label' => '城市',
		'pk' => false,
		'add' => true,
		'edit' => true,
		'html' => false,
		'empty' => false,
		'show' => false,
		'list' => true,
		'type' => 'city',
		'comment' => '',
		'default' => '',
		'SO' => '=',
	),
  'company_id' => 
	array (
		'field' => 'company_id',
		'label' => '公司',
		'pk' => false,
		'add' => true,
		'edit' => true,
		'html' => false,
		'empty' => false,
		'show' => false,
		'list' => true,
		'type' => 'number',
		'comment' => '',
		'default' => '',
		'SO' => '=',
	),  
	'youhui_id' => 
		array (
		'field' => 'youhui_id',
		'label' => '优惠信息',
		'pk' => false,
		'add' => true,
		'edit' => true,
		'html' => false,
		'empty' => false,
		'show' => false,
		'list' => true,
		'type' => 'number',
		'comment' => '',
		'default' => '',
		'SO' => '=',
	),
	'uid' => 
	array (
		'field' => 'uid',
		'label' => '用户ID',
		'pk' => false,
		'add' => true,
		'edit' => true,
		'html' => false,
		'empty' => true,
		'show' => false,
		'list' => true,
		'type' => 'number',
		'comment' => '',
		'default' => '',
		'SO' => '=',
	),
	'mobile' => 
	array (
		'field' => 'mobile',
		'label' => '手机',
		'pk' => false,
		'add' => true,
		'edit' => true,
		'html' => false,
		'empty' => false,
		'show' => false,
		'list' => true,
		'type' => 'mobile',
		'comment' => '',
		'default' => '',
		'SO' => 'like',
	),
	'contact' => 
	array (
		'field' => 'contact',
		'label' => '联系人',
		'pk' => false,
		'add' => true,
		'edit' => true,
		'html' => false,
		'empty' => false,
		'show' => false,
		'list' => true,
		'type' => 'text',
		'comment' => '',
		'default' => '',
		'SO' => 'like',
	),
	'status' => 
	array (
		'field' => 'status',
		'label' => '状态',
		'pk' => false,
		'add' => true,
		'edit' => true,
		'html' => false,
		'empty' => true,
		'show' => false,
		'list' => true,
		'type' => 'number',
		'comment' => '',
		'default' => '',
		'SO' => false,
	),
	'remark' => 
	array (
		'field' => 'remark',
		'label' => '商家备注',
		'pk' => false,
		'add' => true,
		'edit' => true,
		'html' => false,
		'empty' => true,
		'show' => false,
		'list' => true,
		'type' => 'textarea',
		'comment' => '',
		'default' => '',
		'SO' => '',
	),   
	'dateline' => 
	array (
		'field' => 'dateline',
		'label' => '报名时间',
		'pk' => false,
		'add' => true,
		'edit' => true,
		'html' => false,
		'empty' => true,
		'show' => false,
		'list' => true,
		'type' => 'dateline',
		'comment' => '',
		'default' => '',
		'SO' => false,
	),
	'clientip' => 
		array (
		'field' => 'clientip',
		'label' => '报名IP',
		'pk' => false,
		'add' => true,
		'edit' => true,
		'html' => false,
		'empty' => true,
		'show' => false,
		'list' => true,
		'type' => 'clientip',
		'comment' => '',
		'default' => '',
		'SO' => 'like',
	),
);