<?php

/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id: home_tuan.php 3053 2014-01-15 02:00:13Z youyi $
 */
if (!defined('__CORE_DIR')) {
    exit("Access Denied");
}

return array(
    'tuan_id' =>
    array(
        'field' => 'tuan_id',
        'label' => 'ID',
        'pk' => true,
        'add' => false,
        'edit' => false,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'title' =>
    array(
        'field' => 'title',
        'label' => '团装标题',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => 'like',
    ),
    'city_id' =>
    array(
        'field' => 'city_id',
        'label' => '所在城市',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'city',
        'comment' => '',
        'default' => '',
        'SO' => '=',
    ),
    'area_id' =>
    array(
        'field' => 'area_id',
        'label' => '所在地区',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'area',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
	'jieyue' =>
    array(
        'field' => 'jieyue',
        'label' => '节约',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'number',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'home_id' =>
    array(
        'field' => 'home_id',
        'label' => '小区',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'home',
        'comment' => '',
        'default' => '',
        'SO' => '=',
    ),
    'company_id' =>
    array(
        'field' => 'company_id',
        'label' => '公司',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'company',
        'comment' => '',
        'default' => '',
        'SO' => '=',
    ),
    'sign_num' =>
    array(
        'field' => 'sign_num',
        'label' => '报名数',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'qy_num' =>
    array(
        'field' => 'qy_num',
        'label' => '签约数',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'sg_num' =>
    array(
        'field' => 'sg_num',
        'label' => '施工数',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
	'stime' =>
    array(
        'field' => 'stime',
        'label' => '开始时间',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'unixtime',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
	'content' =>
    array(
        'field' => 'content',
        'label' => '内容',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => true,
        'empty' => true,
        'show' => false,
        'list' => false,
        'type' => 'textarea',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'ltime' =>
    array(
        'field' => 'ltime',
        'label' => '到期时间',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'unixtime',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'audit' =>
    array(
        'field' => 'audit',
        'label' => '是否审核',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'audit',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
	'clientip' => 
	array (
		'field' => 'clientip',
		'label' => '创建IP',
		'pk' => false,
		'add' => false,
		'edit' => false,
		'html' => false,
		'empty' => false,
		'show' => false,
		'list' => false,
		'type' => 'clientip',
		'comment' => '',
		'default' => '',
		'SO' => false,
	),
    'dateline' =>
    array(
        'field' => 'dateline',
        'label' => '创建时间',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'dateline',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
);
