<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
  'hetong_id' => 
  array (
    'field' => 'hetong_id',
    'label' => 'ID',
    'pk' => true,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => '=',
  ),
  'zxb_id' => 
  array (
    'field' => 'zxb_id',
    'label' => '装修保ID',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => '=',
  ),
  'uid' => 
  array (
    'field' => 'uid',
    'label' => '业主UID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '业主UID',
    'default' => '',
    'SO' => '=',
  ),
  'company_id' => 
  array (
    'field' => 'company_id',
    'label' => '公司ID',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '公司ID',
    'default' => '',
    'SO' => '=',
  ),
  'total_price' => 
  array (
    'field' => 'total_price',
    'label' => '工程总价',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '工程总价',
    'default' => '',
    'SO' => false,
  ),
  'hetong' => 
  array (
    'field' => 'hetong',
    'label' => '合同压缩包',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'photo',
    'comment' => '合同压缩包，装修公司上传的',
    'default' => '',
    'SO' => false,
  ),
  'yezhu' => 
  array (
    'field' => 'yezhu',
    'label' => '业主姓名',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '业主：甲方',
    'default' => '',
    'SO' => false,
  ),
  'yezhu_phone' => 
  array (
    'field' => 'yezhu_phone',
    'label' => '业主电话',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'yezhu_bank' => 
  array (
    'field' => 'yezhu_bank',
    'label' => '业主银行卡',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'yezhu_status' => 
  array (
    'field' => 'yezhu_status',
    'label' => '业主状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'select',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'yezhu_time' => 
  array (
    'field' => 'yezhu_time',
    'label' => '业主签订时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'unixtime',
    'comment' => '业主签订时间',
    'default' => '',
    'SO' => false,
  ),
  'company' => 
  array (
    'field' => 'company',
    'label' => '公司名',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '公司：乙方',
    'default' => '',
    'SO' => false,
  ),
  'company_phone' =>
  array (
    'field' => 'company_phone',
    'label' => '公司电话',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'company_bank' => 
  array (
    'field' => 'company_bank',
    'label' => '公司银行卡',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'company_status' => 
  array (
    'field' => 'company_status',
    'label' => '公司状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'select',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'company_time' => 
  array (
    'field' => 'company_time',
    'label' => '公司签订时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'unixtime',
    'comment' => '公司签订时间',
    'default' => '',
    'SO' => false,
  ),
  'status' => 
  array (
    'field' => 'status',
    'label' => '平台确认',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'radio',
    'comment' => '平台确认',
    'default' => '',
    'SO' => false,
  ),
  'dateline' => 
  array (
    'field' => 'dateline',
    'label' => '创建时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'dateline',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
);